name = "munduscraft"
author = "DylanLogan2581"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3b93c2a7525101ac1610e9758bb3275a9e0bff3c547b19e72f8eae6c0b5a43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
